# Generated by Django 3.1 on 2020-08-28 08:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200827_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
